### ISSUE TITLE
Detect colors and shapes

### ISSUE THREAD

**Issue by eyantra** [eyantra/image-processing#1]
Complete the given code template to detect colors and shapes

**Comment by PyExtreme** [comment]
@eyantra , I am working on this one. Please assign this to me.

**Comment by MarvinKweyu** [comment]
@PyExtreme came over too late I see. Reach out if you need help?

**Comment by PyExtreme** [comment]
@eyantra @MarvinKweyu , I have made a pull request. Please have a look.

**Comment by Zeraphu** [comment]
I have also added a pull request regarding the same code

**Comment by ven-k** [comment]
Is this issue still open?

**Comment by Likhith-Sugganahalli** [comment]
@eyantra pull request made, last minute i know, awaiting feedback

**Comment by Likhith-Sugganahalli** [comment]
hey, any updates?

**Comment by MarvinKweyu** [comment]
@Likhith-Sugganahalli @PyExtreme @ven-k @Zeraphu  Still waiting for pull requests to be merged

**Comment by Likhith-Sugganahalli** [comment]
@MarvinKweyu I am extremely sorry, i'm new to git, not familiar with the jargon, could you please explain

**Comment by MarvinKweyu** [comment]
Having created an issue and people come in to help, we have to wait for the owner of the project to accept the suggestions made. The suggestions you make are what we call `pull requests`.
